### ISSUE TITLE
Logged in as admin, on Flora Posidonia checkout page, default country appears to be set to "United Kingdom (UK)"

### ISSUE THREAD

**Issue by aubrel** [meitar/flora-posidonia#2]
On WordPress V. 4.8.2, with Flora Posidonia installed from the repository (https://github.com/meitar/flora-posidonia/archive/master.zip) and activated, while logged in as `admin`, with two items in the Cart, on the Checkout page, under "Billing details," the country appears by default as "United Kingdom (UK)." 

This remains to be so even after setting the default City / Country field in WooCommerce's General Settings to "United States (US) - New York".

**Comment by meitar** [comment]
This was caused by a WooCommerce settings mis-configuration issue. The correct configuration is to set the WooCommerce setting for "Default customer location" to the "Shop base address," which has been [documented in our wiki](https://github.com/meitar/flora-posidonia/wiki/WooCommerce-settings/_compare/7bdc94539bf769e7c6abc484019a3c8a4856929f...a92ea1fb0126ef734a5492a19c5db8765e103191).
