### ISSUE TITLE
A Friendlier Order Confirmation Email

### ISSUE THREAD

**Issue by zachmandeville** [meitar/flora-posidonia#31]
I just made an order and received my confirmation email.  It leads with: 
```
= Thank you for your order =

Your order has been received and is now being processed. Your order
details are shown below for your reference:

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

YOU MUST SCHEDULE A PICKUP TO COMPLETE YOUR ORDER.
PLEASE REPLY TO THIS EMAIL WITH SEVERAL PICKUP TIMES AND LOCATIONS
THAT ARE CONVENIENT FOR YOU, NO EARLIER THAN DECEMBER 8, 2017 3:34 PM.
WE WILL SEND YOU A FOLLOW-UP EMAIL WHEN YOUR ORDER IS READY FOR
PICKUP. THANK YOU FOR YOUR BUSINESS!

ORDER NUMBER: 14
```
The first part is great, but I wish the second part was spaced out and lower-cased. The information within is good, but it feels like machine-generated shouting.  

Would it be possible to include all these details, but presented more conversationally?
Also, this is (slightly) silly, but I'd  love one of the ascii flowers that are on the labels to be at the top of this email too.

**Comment by meitar** [comment]
@aubrel I'd love to have this done by the Full Moon Market. I'm not certain what "more conversationally" is like so if you find the time to edit [this email template on the wiki](https://github.com/meitar/flora-posidonia/wiki/Processing-order#email-template), I can move your edits to code and produce a minor or patch release ASAP. Thanks!

**Comment by meitar** [comment]
@aubrel Due to time constraints, I went ahead and made a few minor changes here, [reflected on the wiki as well](https://github.com/meitar/flora-posidonia/wiki/Processing-order/_compare/9d7e775990d4752fce336418724c7eb356456b3e...78c6e7d2b6272e6ad9f89b2d4f8b24eeea80e07d). You can pull down the head of the `issue-31` branch to test this if you want, or if you give me the green light on this issue I'll just roll it into the next point release. (This is a relatively safe change that doesn't need much testing since we're only really changing text, not "functionality" in a meaningful way. Would be nice to get that test harness and continuous integration set up anyway, though. Soon….)
